/**
 * Copyright (c) 2011-2016, Eason Pan(pylxyhome@vip.qq.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jcbase.model;

import java.util.List;

import com.jcbase.model.base.BaseSysUserRole;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole();
	//用于判断用户管理显示列表
	public boolean isHight(String name) {
		List<SysUserRole> sRecords = this.find("select * from sys_user_role where user_id=(select id from sys_user where name="+name+") AND (role_id="+1+" OR role_id="+2+")");
		if(!sRecords.isEmpty()){
			return true;
		}else{
			return false;
		}
	}
	//用于判断用户管理中“编辑”和“角色分配”这两个功能
	public String isGight(String name) {
		List<SysUserRole> sRecords = this.find("select * from sys_user_role where user_id=(select id from sys_user where name="+name+") AND (role_id="+1+" OR role_id="+2+")");
		if(!sRecords.isEmpty()){
			return "yes";
		}else{
			return "no";
		}
	}
	//用于判断运维班
	public boolean isOp(String name) {
		List<SysUserRole> sRecords = this.find("select * from sys_user_role where user_id=(select id from sys_user where name='"+name+"') AND (role_id="+1+" OR role_id="+2+")");
		if(!sRecords.isEmpty()){
			return true;
		}else{
			return false;
		}
	}
	//用于设置变电站和运维班普通用户权限
	public void setRole(String name) {
		int user_id=SysUser.me.getId(name);
		int b=Db.update("insert into sys_user_role (user_id,role_id) values ("+user_id+","+60+")");
		System.out.println(b+"权限设置成功！");
	}
}
