package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensorData<M extends BaseSensorData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setDeviceCode(java.lang.String deviceCode) {
		set("device_code", deviceCode);
	}

	public java.lang.String getDeviceCode() {
		return get("device_code");
	}

	public void setSensorTypeId(java.lang.Long sensorTypeId) {
		set("sensor_type_id", sensorTypeId);
	}

	public java.lang.Long getSensorTypeId() {
		return get("sensor_type_id");
	}

	public void setStatusValue(java.lang.Integer statusValue) {
		set("status_value", statusValue);
	}

	public java.lang.Integer getStatusValue() {
		return get("status_value");
	}

	public void setStatusCurrent(java.lang.Integer statusCurrent) {
		set("status_current", statusCurrent);
	}

	public java.lang.Integer getStatusCurrent() {
		return get("status_current");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
