package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermisedDoor<M extends BasePermisedDoor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setIdenId(java.lang.Long idenId) {
		set("iden_id", idenId);
	}

	public java.lang.Long getIdenId() {
		return get("iden_id");
	}

	public void setPermission(java.lang.Integer permission) {
		set("permission", permission);
	}

	public java.lang.Integer getPermission() {
		return get("permission");
	}

	public void setDoorCode(java.lang.String doorCode) {
		set("door_code", doorCode);
	}

	public java.lang.String getDoorCode() {
		return get("door_code");
	}

}
