package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setActor(java.lang.Integer actor) {
		set("actor", actor);
	}

	public java.lang.Integer getActor() {
		return get("actor");
	}

	public void setLastLogin(java.util.Date lastLogin) {
		set("last_login", lastLogin);
	}

	public java.util.Date getLastLogin() {
		return get("last_login");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setValid(java.lang.Integer valid) {
		set("valid", valid);
	}

	public java.lang.Integer getValid() {
		return get("valid");
	}

	public void setOperationClassId(java.lang.Long operationClassId) {
		set("operation_class_id", operationClassId);
	}

	public java.lang.Long getOperationClassId() {
		return get("operation_class_id");
	}

}
