package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBuilding<M extends BaseBuilding<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setStationId(java.lang.Long stationId) {
		set("station_id", stationId);
	}

	public java.lang.Long getStationId() {
		return get("station_id");
	}

	public void setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
	}

	public java.lang.String getBuildingName() {
		return get("building_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
