package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdentification<M extends BaseIdentification<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAuth(java.lang.String auth) {
		set("auth", auth);
	}

	public java.lang.String getAuth() {
		return get("auth");
	}

	public void setWorker(java.lang.String worker) {
		set("worker", worker);
	}

	public java.lang.String getWorker() {
		return get("worker");
	}

	public void setApproverId(java.lang.Long approverId) {
		set("approver_id", approverId);
	}

	public java.lang.Long getApproverId() {
		return get("approver_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}

	public java.lang.String getTaskName() {
		return get("task_name");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setTicketNum(java.lang.String ticketNum) {
		set("ticket_num", ticketNum);
	}

	public java.lang.String getTicketNum() {
		return get("ticket_num");
	}

	public void setStationId(java.lang.Long stationId) {
		set("station_id", stationId);
	}

	public java.lang.Long getStationId() {
		return get("station_id");
	}

}
