package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensor<M extends BaseSensor<M>> extends Model<M> implements IBean {

	public void setSensorCode(java.lang.String sensorCode) {
		set("sensor_code", sensorCode);
	}

	public java.lang.String getSensorCode() {
		return get("sensor_code");
	}

	public void setBuilding_id(java.lang.Integer building_id) {
		set("building_id", building_id);
	}

	public java.lang.Integer getBuilding_id() {
		return get("building_id");
	}

	public void setAffiliation(java.lang.Long affiliation) {
		set("affiliation", affiliation);
	}

	public java.lang.Long getAffiliation() {
		return get("affiliation");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPort(java.lang.Integer port) {
		set("port", port);
	}

	public java.lang.Integer getPort() {
		return get("port");
	}

}
