package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jcbase.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperationClass<M extends BaseOperationClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOpName(java.lang.String opName) {
		set("op_name", opName);
	}

	public java.lang.String getOpName() {
		return get("op_name");
	}

	public void setOpDesc(java.lang.String opDesc) {
		set("op_desc", opDesc);
	}

	public java.lang.String getOpDesc() {
		return get("op_desc");
	}

	public void setOpAddr(java.lang.String opAddr) {
		set("op_addr", opAddr);
	}

	public java.lang.String getOpAddr() {
		return get("op_addr");
	}

	public void setOpManager(Integer opManager) {
		set("op_manager", opManager);
	}

	public java.lang.Integer getOpManager() {
		return get("op_manager");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
