package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemp<M extends BaseTemp<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAvTemp(java.lang.Double avTemp) {
		set("av_temp", avTemp);
	}

	public java.lang.Double getAvTemp() {
		return get("av_temp");
	}

	public void setTempSensorCode(java.lang.String tempSensorCode) {
		set("temp_sensor_code", tempSensorCode);
	}

	public java.lang.String getTempSensorCode() {
		return get("temp_sensor_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setMaxTemp(java.lang.Double maxTemp) {
		set("max_temp", maxTemp);
	}

	public java.lang.Double getMaxTemp() {
		return get("max_temp");
	}

	public void setMinTemp(java.lang.Double minTemp) {
		set("min_temp", minTemp);
	}

	public java.lang.Double getMinTemp() {
		return get("min_temp");
	}

}
