package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAlert<M extends BaseAlert<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTypeId(java.lang.Long typeId) {
		set("type_id", typeId);
	}

	public java.lang.Long getTypeId() {
		return get("type_id");
	}

	public void setAlertObjCode(java.lang.String alertObjCode) {
		set("alert_obj_code", alertObjCode);
	}

	public java.lang.String getAlertObjCode() {
		return get("alert_obj_code");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Long status) {
		set("status", status);
	}

	public java.lang.Long getStatus() {
		return get("status");
	}

}
