package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStation<M extends BaseStation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOpId(java.lang.Long opId) {
		set("op_id", opId);
	}

	public java.lang.Long getOpId() {
		return get("op_id");
	}

	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}

	public java.lang.String getStationName() {
		return get("station_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStationDesc(java.lang.String stationDesc) {
		set("station_desc", stationDesc);
	}

	public java.lang.String getStationDesc() {
		return get("station_desc");
	}

	public void setStationAddr(java.lang.String stationAddr) {
		set("station_addr", stationAddr);
	}

	public java.lang.String getStationAddr() {
		return get("station_addr");
	}

	public void setStationManager(java.lang.Long stationManager) {
		set("station_manager", stationManager);
	}

	public java.lang.Long getStationManager() {
		return get("station_manager");
	}

}
