package com.yanxin.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("alert", "id", Alert.class);
		arp.addMapping("alert_type", "id", AlertType.class);
		arp.addMapping("building", "id", Building.class);
		arp.addMapping("identification", "id", Identification.class);
		arp.addMapping("images", "id", Images.class);
		arp.addMapping("layer", "id", Layer.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("log_type", "id", LogType.class);
		arp.addMapping("operation_class", "id", OperationClass.class);
		arp.addMapping("permised_door", "id", PermisedDoor.class);
		arp.addMapping("room", "id", Room.class);
		arp.addMapping("sensor", "sensor_code", Sensor.class);
		arp.addMapping("sensor_data", "id", SensorData.class);
		arp.addMapping("sensor_type", "id", SensorType.class);
		arp.addMapping("station", "id", Station.class);
		arp.addMapping("temp", "id", Temp.class);
		arp.addMapping("user", "id", User.class);
	}
}

