package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseAlertType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlertType extends BaseAlertType<AlertType> {
	public static final AlertType dao = new AlertType().dao();
}
