package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseAlert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Alert extends BaseAlert<Alert> {
	public static final Alert dao = new Alert().dao();
}
