package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseBuilding;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Building extends BaseBuilding<Building> {
	public static final Building dao = new Building().dao();
}
