package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseIdentification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Identification extends BaseIdentification<Identification> {
	public static final Identification dao = new Identification().dao();
}
