package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Images extends BaseImages<Images> {
	public static final Images dao = new Images().dao();
}
