package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseLayer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Layer extends BaseLayer<Layer> {
	public static final Layer dao = new Layer().dao();
}
