package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseLogType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogType extends BaseLogType<LogType> {
	public static final LogType dao = new LogType().dao();
}
