package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseOperationClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperationClass extends BaseOperationClass<OperationClass> {
	public static final OperationClass dao = new OperationClass().dao();
	
}
