package com.yanxin.common.model;

import com.yanxin.common.model.base.BasePermisedDoor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermisedDoor extends BasePermisedDoor<PermisedDoor> {
	public static final PermisedDoor dao = new PermisedDoor().dao();
}
