package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseSensor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sensor extends BaseSensor<Sensor> {
	
	public static final Sensor dao = new Sensor().dao();
	
}
