package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseSensorData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensorData extends BaseSensorData<SensorData> {
	public static final SensorData dao = new SensorData().dao();
}
