package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseSensorType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensorType extends BaseSensorType<SensorType> {
	public static final SensorType dao = new SensorType().dao();
}
