package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Station extends BaseStation<Station> {
	public static final Station dao = new Station().dao();
}
