package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Temp extends BaseTemp<Temp> {
	public static final Temp dao = new Temp().dao();
}
